@RentalCarSystem.API_HostAddress = https://localhost:7039/api

GET {{RentalCarSystem.API_HostAddress}}/v1/rental/2024-04-01/2024-04-30
Accept: application/json

###

GET {{RentalCarSystem.API_HostAddress}}/v2/rental/2024-04-01/2024-04-30
Accept: application/json

###

GET {{RentalCarSystem.API_HostAddress}}/v1/car
Accept: application/json

###

GET {{RentalCarSystem.API_HostAddress}}/v1/car/3
Accept: application/json

###

POST {{RentalCarSystem.API_HostAddress}}/v1/car
Accept: application/json
Content-Type: application/json

{
  "id": 0,
  "model": "Ferrari",
  "year": 1999,
  "color": "Red",
  "dailyPrice": 100000,
  "available": true
}